spring.application.name=digitalfix-ms-workorders
# Puerto local independiente del BFF y de Catalog
server.port=8082

# Conexión Oracle RDS mediante variables de entorno
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Preparación del esquema durante el desarrollo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false