spring.application.name=digitalfix-ms-workorders
# Puerto local independiente del BFF y de Catalog
server.port=8082

# Conexion Oracle RDS mediante variables de entorno
spring.datasource.url=jdbc:oracle:thin:@//digitalfix.c1ligwfwziy9.us-east-1.rds.amazonaws.com/ORCL
spring.datasource.username=admin
spring.datasource.password=Duocvalparaiso.2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Preparación del esquema durante el desarrollo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/762b016c-dc33-4db0-ad42-44f32afe71f4/v2.0
# Identificador de DigitalFix API: audiencia esperada del access token
spring.security.oauth2.resourceserver.jwt.audiences=85329d90-58f8-4317-a820-452599b3b04c