spring.application.name=digitalfix-ms-workorders
# Puerto local independiente del BFF y de Catalog
server.port=8082

# Conexion Oracle RDS mediante variables de entorno
spring.datasource.url=jdbc:oracle:thin:@//digitalfix.c1ligwfwziy9.us-east-1.rds.amazonaws.com/ORCL
spring.datasource.username=admin
spring.datasource.password=Duocvalparaiso.2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Preparación del esquema durante el desarrollo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false